# Generated by Django 5.2 on 2025-04-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
